import Navbar from '@/app/components/navbar';
import { Manrope } from 'next/font/google';
import { cookies } from 'next/headers';
import { PropsWithChildren } from 'react';
import './globals.css';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const cookieStore = cookies();
  const theme = cookieStore.get('theme');

  return (
    <html lang="es" className={theme?.value || 'dark'}>
      <body className={`${manrope.className} min-h-screen max-w-screen-xl min-w-min gap-4 m-auto flex flex-col transition-colors text-black dark:text-white bg-neutral-100 dark:bg-black`}>
        <Navbar />
        {children}
        <footer className="h-32"></footer>
      </body>
    </html>
  );
}
