import Navbar from '@/app/components/navbar';
import './globals.css';
import { Manrope } from 'next/font/google';
import { cookies } from 'next/headers';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const cookieStore = cookies();
  // const theme = cookieStore.get('theme');

  return (
    // <html lang="es" className={theme?.value || 'dark'} >
    <html lang="es">
      <body className={`${manrope.className} min-w-min text-black dark:text-white bg-neutral-100 dark:bg-black`}>
        <Navbar />
        {children}
        <footer className="h-32"></footer>
      </body>
    </html>
  );
}
